[package]
name = "g4_data_filter"
version = "2.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
csv = "1.2"
lazy_static = "1.4.0"
